# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kuma/pico/project/TinySeq

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kuma/pico/project/TinySeq

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kuma/pico/project/TinySeq/CMakeFiles /home/kuma/pico/project/TinySeq/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kuma/pico/project/TinySeq/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ELF2UF2Build

# Build rule for target.
ELF2UF2Build: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ELF2UF2Build
.PHONY : ELF2UF2Build

# fast build rule for target.
ELF2UF2Build/fast:
	$(MAKE) -f CMakeFiles/ELF2UF2Build.dir/build.make CMakeFiles/ELF2UF2Build.dir/build
.PHONY : ELF2UF2Build/fast

#=============================================================================
# Target rules for targets named tinyseq

# Build rule for target.
tinyseq: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyseq
.PHONY : tinyseq

# fast build rule for target.
tinyseq/fast:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/build
.PHONY : tinyseq/fast

#=============================================================================
# Target rules for targets named bs2_default_padded_checksummed_asm

# Build rule for target.
bs2_default_padded_checksummed_asm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bs2_default_padded_checksummed_asm
.PHONY : bs2_default_padded_checksummed_asm

# fast build rule for target.
bs2_default_padded_checksummed_asm/fast:
	$(MAKE) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_padded_checksummed_asm.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_padded_checksummed_asm.dir/build
.PHONY : bs2_default_padded_checksummed_asm/fast

#=============================================================================
# Target rules for targets named bs2_default_bin

# Build rule for target.
bs2_default_bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bs2_default_bin
.PHONY : bs2_default_bin

# fast build rule for target.
bs2_default_bin/fast:
	$(MAKE) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_bin.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_bin.dir/build
.PHONY : bs2_default_bin/fast

#=============================================================================
# Target rules for targets named bs2_default

# Build rule for target.
bs2_default: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bs2_default
.PHONY : bs2_default

# fast build rule for target.
bs2_default/fast:
	$(MAKE) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/build
.PHONY : bs2_default/fast

home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.obj: home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.c.obj

home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.i: home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.c.i

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.c.i
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.c.i

home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.s: home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.c.s

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.c.s
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.c.s

home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.obj: home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.c.obj

home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.i: home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.c.i

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.c.i
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.c.i

home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.s: home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.c.s

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.c.s
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.c.s

home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.obj: home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.c.obj

home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.i: home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.c.i

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.c.i
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.c.i

home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.s: home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.c.s

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.c.s
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.c.s

home/kuma/pico/pico-sdk/src/common/pico_sync/sem.obj: home/kuma/pico/pico-sdk/src/common/pico_sync/sem.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/sem.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/common/pico_sync/sem.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_sync/sem.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/sem.c.obj

home/kuma/pico/pico-sdk/src/common/pico_sync/sem.i: home/kuma/pico/pico-sdk/src/common/pico_sync/sem.c.i

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/sem.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/common/pico_sync/sem.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_sync/sem.c.i
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/sem.c.i

home/kuma/pico/pico-sdk/src/common/pico_sync/sem.s: home/kuma/pico/pico-sdk/src/common/pico_sync/sem.c.s

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/sem.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/common/pico_sync/sem.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_sync/sem.c.s
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_sync/sem.c.s

home/kuma/pico/pico-sdk/src/common/pico_time/time.obj: home/kuma/pico/pico-sdk/src/common/pico_time/time.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_time/time.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/common/pico_time/time.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_time/time.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_time/time.c.obj

home/kuma/pico/pico-sdk/src/common/pico_time/time.i: home/kuma/pico/pico-sdk/src/common/pico_time/time.c.i

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_time/time.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/common/pico_time/time.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_time/time.c.i
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_time/time.c.i

home/kuma/pico/pico-sdk/src/common/pico_time/time.s: home/kuma/pico/pico-sdk/src/common/pico_time/time.c.s

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_time/time.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/common/pico_time/time.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_time/time.c.s
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_time/time.c.s

home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.obj: home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.c.obj

home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.i: home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.c.i

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.c.i
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.c.i

home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.s: home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.c.s

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.c.s
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.c.s

home/kuma/pico/pico-sdk/src/common/pico_util/datetime.obj: home/kuma/pico/pico-sdk/src/common/pico_util/datetime.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/datetime.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/common/pico_util/datetime.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_util/datetime.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/datetime.c.obj

home/kuma/pico/pico-sdk/src/common/pico_util/datetime.i: home/kuma/pico/pico-sdk/src/common/pico_util/datetime.c.i

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/datetime.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/common/pico_util/datetime.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_util/datetime.c.i
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/datetime.c.i

home/kuma/pico/pico-sdk/src/common/pico_util/datetime.s: home/kuma/pico/pico-sdk/src/common/pico_util/datetime.c.s

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/datetime.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/common/pico_util/datetime.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_util/datetime.c.s
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/datetime.c.s

home/kuma/pico/pico-sdk/src/common/pico_util/pheap.obj: home/kuma/pico/pico-sdk/src/common/pico_util/pheap.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/pheap.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/common/pico_util/pheap.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_util/pheap.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/pheap.c.obj

home/kuma/pico/pico-sdk/src/common/pico_util/pheap.i: home/kuma/pico/pico-sdk/src/common/pico_util/pheap.c.i

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/pheap.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/common/pico_util/pheap.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_util/pheap.c.i
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/pheap.c.i

home/kuma/pico/pico-sdk/src/common/pico_util/pheap.s: home/kuma/pico/pico-sdk/src/common/pico_util/pheap.c.s

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/pheap.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/common/pico_util/pheap.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_util/pheap.c.s
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/pheap.c.s

home/kuma/pico/pico-sdk/src/common/pico_util/queue.obj: home/kuma/pico/pico-sdk/src/common/pico_util/queue.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/queue.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/common/pico_util/queue.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_util/queue.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/queue.c.obj

home/kuma/pico/pico-sdk/src/common/pico_util/queue.i: home/kuma/pico/pico-sdk/src/common/pico_util/queue.c.i

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/queue.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/common/pico_util/queue.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_util/queue.c.i
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/queue.c.i

home/kuma/pico/pico-sdk/src/common/pico_util/queue.s: home/kuma/pico/pico-sdk/src/common/pico_util/queue.c.s

.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/queue.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/common/pico_util/queue.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/common/pico_util/queue.c.s
.PHONY : home/kuma/pico/pico-sdk/src/common/pico_util/queue.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_divider/divider.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_divider/divider.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s

home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj: home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.i: home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i

home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.s: home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_divider/divider.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_divider/divider.S.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_divider/divider.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_divider/divider.S.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_divider/divider.S.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_divider/divider.S.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s

home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj: home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj

# target to build an object file
home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj

home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i: home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i

# target to preprocess a source file
home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i

home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s: home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s

.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s

# target to generate assembly for a file
home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s
.PHONY : home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s

main-pico.obj: main-pico.c.obj

.PHONY : main-pico.obj

# target to build an object file
main-pico.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/main-pico.c.obj
.PHONY : main-pico.c.obj

main-pico.i: main-pico.c.i

.PHONY : main-pico.i

# target to preprocess a source file
main-pico.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/main-pico.c.i
.PHONY : main-pico.c.i

main-pico.s: main-pico.c.s

.PHONY : main-pico.s

# target to generate assembly for a file
main-pico.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/main-pico.c.s
.PHONY : main-pico.c.s

xprintf/src/xprintf.obj: xprintf/src/xprintf.c.obj

.PHONY : xprintf/src/xprintf.obj

# target to build an object file
xprintf/src/xprintf.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/xprintf/src/xprintf.c.obj
.PHONY : xprintf/src/xprintf.c.obj

xprintf/src/xprintf.i: xprintf/src/xprintf.c.i

.PHONY : xprintf/src/xprintf.i

# target to preprocess a source file
xprintf/src/xprintf.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/xprintf/src/xprintf.c.i
.PHONY : xprintf/src/xprintf.c.i

xprintf/src/xprintf.s: xprintf/src/xprintf.c.s

.PHONY : xprintf/src/xprintf.s

# target to generate assembly for a file
xprintf/src/xprintf.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/xprintf/src/xprintf.c.s
.PHONY : xprintf/src/xprintf.c.s

zForth/forth/core.obj: zForth/forth/core.c.obj

.PHONY : zForth/forth/core.obj

# target to build an object file
zForth/forth/core.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/zForth/forth/core.c.obj
.PHONY : zForth/forth/core.c.obj

zForth/forth/core.i: zForth/forth/core.c.i

.PHONY : zForth/forth/core.i

# target to preprocess a source file
zForth/forth/core.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/zForth/forth/core.c.i
.PHONY : zForth/forth/core.c.i

zForth/forth/core.s: zForth/forth/core.c.s

.PHONY : zForth/forth/core.s

# target to generate assembly for a file
zForth/forth/core.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/zForth/forth/core.c.s
.PHONY : zForth/forth/core.c.s

zForth/src/pico/zmain.obj: zForth/src/pico/zmain.c.obj

.PHONY : zForth/src/pico/zmain.obj

# target to build an object file
zForth/src/pico/zmain.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/zForth/src/pico/zmain.c.obj
.PHONY : zForth/src/pico/zmain.c.obj

zForth/src/pico/zmain.i: zForth/src/pico/zmain.c.i

.PHONY : zForth/src/pico/zmain.i

# target to preprocess a source file
zForth/src/pico/zmain.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/zForth/src/pico/zmain.c.i
.PHONY : zForth/src/pico/zmain.c.i

zForth/src/pico/zmain.s: zForth/src/pico/zmain.c.s

.PHONY : zForth/src/pico/zmain.s

# target to generate assembly for a file
zForth/src/pico/zmain.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/zForth/src/pico/zmain.c.s
.PHONY : zForth/src/pico/zmain.c.s

zForth/src/zforth/zforth.obj: zForth/src/zforth/zforth.c.obj

.PHONY : zForth/src/zforth/zforth.obj

# target to build an object file
zForth/src/zforth/zforth.c.obj:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/zForth/src/zforth/zforth.c.obj
.PHONY : zForth/src/zforth/zforth.c.obj

zForth/src/zforth/zforth.i: zForth/src/zforth/zforth.c.i

.PHONY : zForth/src/zforth/zforth.i

# target to preprocess a source file
zForth/src/zforth/zforth.c.i:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/zForth/src/zforth/zforth.c.i
.PHONY : zForth/src/zforth/zforth.c.i

zForth/src/zforth/zforth.s: zForth/src/zforth/zforth.c.s

.PHONY : zForth/src/zforth/zforth.s

# target to generate assembly for a file
zForth/src/zforth/zforth.c.s:
	$(MAKE) -f CMakeFiles/tinyseq.dir/build.make CMakeFiles/tinyseq.dir/zForth/src/zforth/zforth.c.s
.PHONY : zForth/src/zforth/zforth.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ELF2UF2Build"
	@echo "... tinyseq"
	@echo "... bs2_default_padded_checksummed_asm"
	@echo "... bs2_default_bin"
	@echo "... bs2_default"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.obj"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.i"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_sync/critical_section.s"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.obj"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.i"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_sync/lock_core.s"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.obj"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.i"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_sync/mutex.s"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_sync/sem.obj"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_sync/sem.i"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_sync/sem.s"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_time/time.obj"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_time/time.i"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_time/time.s"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.obj"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.i"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_time/timeout_helper.s"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_util/datetime.obj"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_util/datetime.i"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_util/datetime.s"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_util/pheap.obj"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_util/pheap.i"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_util/pheap.s"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_util/queue.obj"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_util/queue.i"
	@echo "... home/kuma/pico/pico-sdk/src/common/pico_util/queue.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_claim/claim.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_divider/divider.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_flash/flash.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_pll/pll.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_spi/spi.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_sync/sync.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_timer/timer.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_uart/uart.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_divider/divider.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_math.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_math.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_platform/platform.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_printf/printf.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i"
	@echo "... home/kuma/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s"
	@echo "... main-pico.obj"
	@echo "... main-pico.i"
	@echo "... main-pico.s"
	@echo "... xprintf/src/xprintf.obj"
	@echo "... xprintf/src/xprintf.i"
	@echo "... xprintf/src/xprintf.s"
	@echo "... zForth/forth/core.obj"
	@echo "... zForth/forth/core.i"
	@echo "... zForth/forth/core.s"
	@echo "... zForth/src/pico/zmain.obj"
	@echo "... zForth/src/pico/zmain.i"
	@echo "... zForth/src/pico/zmain.s"
	@echo "... zForth/src/zforth/zforth.obj"
	@echo "... zForth/src/zforth/zforth.i"
	@echo "... zForth/src/zforth/zforth.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

